name: deepconvlstm
dataset_name: opportunity
devices: ['cuda:0']
save_conv_features_during_training: False
save_lstm_features_during_training: True
anno_json: [
  'data/opportunity_adl_data/annotations/opportunity_split_1.json',
  'data/opportunity_adl_data/annotations/opportunity_split_2.json',
  'data/opportunity_adl_data/annotations/opportunity_split_3.json'
]
dataset: {
  sens_folder: ./data/opportunity_adl_data/raw_clipped_scaled,
  lstm_feat_folder: ./data/opportunity_adl_data/lstm_inertial_norm/inertial_features/60_frames_30_stride,
  input_dim: 113,
  sampling_rate: 30,
  num_classes: 17,
  window_size: 30,
  window_overlap: 50,
  tiou_thresholds: [0.3, 0.4, 0.5, 0.6, 0.7]
}
model: {
  conv_kernels: 64,
  conv_kernel_size: 7,
  lstm_units: 1024,
  lstm_layers: 2,
  dropout: 0.5
}
train_cfg: {
  lr: 0.0000015,
  lr_decay: 0.9,
  lr_step: 10,
  epochs: 35,
  weight_decay: 0.000001,
  weight_init: 'xavier_normal',
  weighted_loss: True,
}
loader: {
  batch_size: 100,
}